### ISSUE TITLE
Target GNOME Circle

### ISSUE THREAD

**Issue by gregorni** [GeopJr/libadwaita.cr#5]
As of two days ago, GTK language bindings can now apply for GNOME Circle: https://gitlab.gnome.org/Teams/Board/-/issues/397

If these bindings are production-ready, you might consider applying.

If not, could this be a goal to target?

**Comment by GeopJr** [comment]
Considering most of the bindings work is on the generator (this repo just defines the libadwaita config and includes some helper functions), it's up to Hugo to decide when the bindings are production-ready. I'd say there's other issues to deal with even after the bindings are declared production-ready, specifically:
- Central org or at least someone to manage everything from gi-crystal to libadwaita.cr. It's going to be difficult and overwhelming to newcommers if I apply libadwaita.cr to circle and then have to forward every issue to gi-crystal
- Guides, Apps, Extensions etc. Ultimate-gtk4-crystal-guide is ok at best, but it mostly documents **my** workflow from when I started Collision. Since then gi-crystal added support for many gobject patterns from subclassing to properties and signals. A good guide needs to follow upstream closely like the gtk-rs book. For apps, AFAIK there's only Collision and Tijolo (which I don't think has migrated fully to GTK4 and doesn't follow our HIG). Maybe AHK_X11 though it's GTK3

I had started a discussion on this ages ago on gi-crystal if you want to keep track of it https://github.com/hugopl/gi-crystal/discussions/16

Ultimately, applying to circle is something gi-crystal :shrug:

**Comment by gregorni** [comment]
> I had started a discussion on this ages ago on gi-crystal if you want to keep track of it hugopl/gi-crystal#16

Thanks! I wasn't sure where to bring this up, so I posted it here. I'll look at the gi repo.

**Comment by hugopl** [comment]
I don't think gi-crystal is production ready yet, it's possible to write gtk applications with it, for sure, but there are tons of GTK features not yet implemented in the generator nether GTK4 bindings.

My current target is to be able to write Tijolo with the minimum amount of work arounds possible, I plan to do a release of the GTK4 version in December, but even so there will stay tons of features missing.

I think a port of the gtk-rs book to Crystal would be a good start to know the missing features and also help newcomers, saving us some work about book structure, etc.

Anyway, having it on gnome circle is good as a ultimate target.

**Comment by hugopl** [comment]
the funny part is that is my comment 1 year ago in the gi-crystal issue I said that I think it's production ready, and one year later I changed my mind 😄

**Comment by GeopJr** [comment]
Something else to consider in the long run is adding Crystal support to meson. It obviously won't have any benefit on the Crystal side of things but it will manage all the metadata from translations to installing icons. I've been using a Makefile as a substitute https://github.com/GeopJr/Collision/blob/main/Makefile but it has caused package maintainers to package it wrongly or incompletely.

Also a flatpak crystal sdk extension because the current situation of manually installing crystal is annoying

I'll take a closer look into both of these at some point :weary:

**Comment by hugopl** [comment]
I use Makefiles too, good thing is that it's available everywhere, bad thing is that we need to write it from scratch every time.

I didn't stop to think about translations in gi-crystal yet, maybe because there are other (IMO more important) stuff that still not ready.

**Comment by GeopJr** [comment]
> I didn't stop to think about translations in gi-crystal yet, maybe because there are other (IMO more important) stuff that still not ready.

I don't think there's anything that needs to be done from gi-crystal's side. Translations work on Collision using gettext (bindings https://github.com/GeopJr/gettext.cr), I have documented it https://ultimate-gtk4-crystal-guide.geopjr.dev/en/extra/gettext.html

But package maintainers end up not installing them at all sometimes :shrug: 

https://github.com/GeopJr/Collision/blob/ddec680e228717d63904658cfda501cf4122f66a/Makefile#L20-L27
```Makefile
mo:
	mkdir -p $(PO_LOCATION)/mo
	for lang in `cat "$(PO_LOCATION)/LINGUAS"`; do \
		if [[ "$$lang" == 'en' || "$$lang" == '' ]]; then continue; fi; \
		mkdir -p "$(PREFIX)$(LOCALE_LOCATION)/$$lang/LC_MESSAGES"; \
		msgfmt "$(PO_LOCATION)/$$lang.po" -o "$(PO_LOCATION)/mo/$$lang.mo"; \
		install -D -m 0644 "$(PO_LOCATION)/mo/$$lang.mo" "$(PREFIX)$(LOCALE_LOCATION)/$$lang/LC_MESSAGES/dev.geopjr.Collision.mo"; \
	done
```
